name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest]
        include:
        - os: windows-latest
          generator: '-G Ninja --preset arm64ec'
        - os: ubuntu-latest
          generator: '-G "Unix Makefiles"'
        - os: macOS-latest
          generator: '-G "Unix Makefiles"'  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{ matrix.generator }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

