name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
    buildWindowsARM64EC:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3

        - name: Do stuff
          run: | 
            dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
            echo %PATH%
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\vsdevcmd.bat" -arch=arm64 -host_arch=amd64
            REM call set PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build
            echo %PATH%
            cmake --debug-output -B ${{github.workspace}}/build --preset arm64ec
            cmake --build ${{github.workspace}}/build --config Release
          shell: cmd
          

